package com.matoosfe.ecommerce.modelo;
// Generated 05/06/2019 19:11:01 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetalleFactura generated by hbm2java
 */
@Entity
@Table(name = "detalle_factura")
public class DetalleFactura implements java.io.Serializable {

	private int idDetfac;
	private Factura factura;
	private ProductoHasProveedor productoHasProveedor;
	private int canDetfac;
	private String obsDetfac;
	private BigDecimal subtotalDetfac;
	private BigDecimal ivaDetfac;
	private BigDecimal totalDetfac;

	public DetalleFactura() {
	}

	public DetalleFactura(int idDetfac, Factura factura, ProductoHasProveedor productoHasProveedor, int canDetfac,
			String obsDetfac, BigDecimal subtotalDetfac, BigDecimal ivaDetfac, BigDecimal totalDetfac) {
		this.idDetfac = idDetfac;
		this.factura = factura;
		this.productoHasProveedor = productoHasProveedor;
		this.canDetfac = canDetfac;
		this.obsDetfac = obsDetfac;
		this.subtotalDetfac = subtotalDetfac;
		this.ivaDetfac = ivaDetfac;
		this.totalDetfac = totalDetfac;
	}

	@Id

	@Column(name = "id_detfac", unique = true, nullable = false)
	public int getIdDetfac() {
		return this.idDetfac;
	}

	public void setIdDetfac(int idDetfac) {
		this.idDetfac = idDetfac;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_fac", nullable = false)
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "id_pro", referencedColumnName = "id_pro", nullable = false),
			@JoinColumn(name = "id_prov", referencedColumnName = "id_prov", nullable = false) })
	public ProductoHasProveedor getProductoHasProveedor() {
		return this.productoHasProveedor;
	}

	public void setProductoHasProveedor(ProductoHasProveedor productoHasProveedor) {
		this.productoHasProveedor = productoHasProveedor;
	}

	@Column(name = "can_detfac", nullable = false)
	public int getCanDetfac() {
		return this.canDetfac;
	}

	public void setCanDetfac(int canDetfac) {
		this.canDetfac = canDetfac;
	}

	@Column(name = "obs_detfac", nullable = false, length = 45)
	public String getObsDetfac() {
		return this.obsDetfac;
	}

	public void setObsDetfac(String obsDetfac) {
		this.obsDetfac = obsDetfac;
	}

	@Column(name = "subtotal_detfac", nullable = false, precision = 10)
	public BigDecimal getSubtotalDetfac() {
		return this.subtotalDetfac;
	}

	public void setSubtotalDetfac(BigDecimal subtotalDetfac) {
		this.subtotalDetfac = subtotalDetfac;
	}

	@Column(name = "iva_detfac", nullable = false, precision = 10)
	public BigDecimal getIvaDetfac() {
		return this.ivaDetfac;
	}

	public void setIvaDetfac(BigDecimal ivaDetfac) {
		this.ivaDetfac = ivaDetfac;
	}

	@Column(name = "total_detfac", nullable = false, precision = 10)
	public BigDecimal getTotalDetfac() {
		return this.totalDetfac;
	}

	public void setTotalDetfac(BigDecimal totalDetfac) {
		this.totalDetfac = totalDetfac;
	}

}
