package com.matoosfe.ecommerce.modelo;
// Generated 03/06/2019 20:42:35 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto")
public class Producto implements java.io.Serializable {

	private int idPro;
	private TipoProducto tipoProducto;
	private String nombrePro;
	private String descripcionPro;
	private BigDecimal precioPro;
	private Date fechaCadPro;
	private Set<ProductoHasProveedor> productoHasProveedors = new HashSet<ProductoHasProveedor>(0);

	public Producto() {
	}

	public Producto(int idPro, TipoProducto tipoProducto, String nombrePro, BigDecimal precioPro) {
		this.idPro = idPro;
		this.tipoProducto = tipoProducto;
		this.nombrePro = nombrePro;
		this.precioPro = precioPro;
	}

	public Producto(int idPro, TipoProducto tipoProducto, String nombrePro, String descripcionPro, BigDecimal precioPro,
			Date fechaCadPro, Set<ProductoHasProveedor> productoHasProveedors) {
		this.idPro = idPro;
		this.tipoProducto = tipoProducto;
		this.nombrePro = nombrePro;
		this.descripcionPro = descripcionPro;
		this.precioPro = precioPro;
		this.fechaCadPro = fechaCadPro;
		this.productoHasProveedors = productoHasProveedors;
	}

	@Id

	@Column(name = "id_pro", unique = true, nullable = false)
	public int getIdPro() {
		return this.idPro;
	}

	public void setIdPro(int idPro) {
		this.idPro = idPro;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tip_pro", nullable = false)
	public TipoProducto getTipoProducto() {
		return this.tipoProducto;
	}

	public void setTipoProducto(TipoProducto tipoProducto) {
		this.tipoProducto = tipoProducto;
	}

	@Column(name = "nombre_pro", nullable = false, length = 25)
	public String getNombrePro() {
		return this.nombrePro;
	}

	public void setNombrePro(String nombrePro) {
		this.nombrePro = nombrePro;
	}

	@Column(name = "descripcion_pro", length = 200)
	public String getDescripcionPro() {
		return this.descripcionPro;
	}

	public void setDescripcionPro(String descripcionPro) {
		this.descripcionPro = descripcionPro;
	}

	@Column(name = "precio_pro", nullable = false, precision = 10)
	public BigDecimal getPrecioPro() {
		return this.precioPro;
	}

	public void setPrecioPro(BigDecimal precioPro) {
		this.precioPro = precioPro;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha_cad_pro", length = 10)
	public Date getFechaCadPro() {
		return this.fechaCadPro;
	}

	public void setFechaCadPro(Date fechaCadPro) {
		this.fechaCadPro = fechaCadPro;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "producto")
	public Set<ProductoHasProveedor> getProductoHasProveedors() {
		return this.productoHasProveedors;
	}

	public void setProductoHasProveedors(Set<ProductoHasProveedor> productoHasProveedors) {
		this.productoHasProveedors = productoHasProveedors;
	}

}
