package com.matoosfe.ecommerce.modelo;
// Generated 05/06/2019 19:11:01 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProductoHasProveedorId generated by hbm2java
 */
@Embeddable
public class ProductoHasProveedorId implements java.io.Serializable {

	private int idPro;
	private int idProv;

	public ProductoHasProveedorId() {
	}

	public ProductoHasProveedorId(int idPro, int idProv) {
		this.idPro = idPro;
		this.idProv = idProv;
	}

	@Column(name = "id_pro", nullable = false)
	public int getIdPro() {
		return this.idPro;
	}

	public void setIdPro(int idPro) {
		this.idPro = idPro;
	}

	@Column(name = "id_prov", nullable = false)
	public int getIdProv() {
		return this.idProv;
	}

	public void setIdProv(int idProv) {
		this.idProv = idProv;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProductoHasProveedorId))
			return false;
		ProductoHasProveedorId castOther = (ProductoHasProveedorId) other;

		return (this.getIdPro() == castOther.getIdPro()) && (this.getIdProv() == castOther.getIdProv());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPro();
		result = 37 * result + this.getIdProv();
		return result;
	}

}
