package com.matoosfe.ecommerce.modelo;
// Generated 03/06/2019 20:42:35 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductoHasProveedor generated by hbm2java
 */
@Entity
@Table(name = "producto_has_proveedor")
public class ProductoHasProveedor implements java.io.Serializable {

	private ProductoHasProveedorId id;
	private Producto producto;
	private Proveedor proveedor;
	private Date fecha;
	private Set<DetalleFactura> detalleFacturas = new HashSet<DetalleFactura>(0);

	public ProductoHasProveedor() {
	}

	public ProductoHasProveedor(ProductoHasProveedorId id, Producto producto, Proveedor proveedor, Date fecha) {
		this.id = id;
		this.producto = producto;
		this.proveedor = proveedor;
		this.fecha = fecha;
	}

	public ProductoHasProveedor(ProductoHasProveedorId id, Producto producto, Proveedor proveedor, Date fecha,
			Set<DetalleFactura> detalleFacturas) {
		this.id = id;
		this.producto = producto;
		this.proveedor = proveedor;
		this.fecha = fecha;
		this.detalleFacturas = detalleFacturas;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idPro", column = @Column(name = "id_pro", nullable = false)),
			@AttributeOverride(name = "idProv", column = @Column(name = "id_prov", nullable = false)) })
	public ProductoHasProveedorId getId() {
		return this.id;
	}

	public void setId(ProductoHasProveedorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_pro", nullable = false, insertable = false, updatable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_prov", nullable = false, insertable = false, updatable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fecha", nullable = false, length = 10)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productoHasProveedor")
	public Set<DetalleFactura> getDetalleFacturas() {
		return this.detalleFacturas;
	}

	public void setDetalleFacturas(Set<DetalleFactura> detalleFacturas) {
		this.detalleFacturas = detalleFacturas;
	}

}
