package com.matoosfe.ecommerce.modelo;
// Generated 03/06/2019 20:42:35 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name = "proveedor")
public class Proveedor implements java.io.Serializable {

	private int idProv;
	private String nombrePer;
	private Set<ProductoHasProveedor> productoHasProveedors = new HashSet<ProductoHasProveedor>(0);

	public Proveedor() {
	}

	public Proveedor(int idProv, String nombrePer) {
		this.idProv = idProv;
		this.nombrePer = nombrePer;
	}

	public Proveedor(int idProv, String nombrePer, Set<ProductoHasProveedor> productoHasProveedors) {
		this.idProv = idProv;
		this.nombrePer = nombrePer;
		this.productoHasProveedors = productoHasProveedors;
	}

	@Id

	@Column(name = "id_prov", unique = true, nullable = false)
	public int getIdProv() {
		return this.idProv;
	}

	public void setIdProv(int idProv) {
		this.idProv = idProv;
	}

	@Column(name = "nombre_per", nullable = false, length = 45)
	public String getNombrePer() {
		return this.nombrePer;
	}

	public void setNombrePer(String nombrePer) {
		this.nombrePer = nombrePer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proveedor")
	public Set<ProductoHasProveedor> getProductoHasProveedors() {
		return this.productoHasProveedors;
	}

	public void setProductoHasProveedors(Set<ProductoHasProveedor> productoHasProveedors) {
		this.productoHasProveedors = productoHasProveedors;
	}

}
