package com.matoosfe.ecommerce.modelo;
// Generated 03/06/2019 20:42:35 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "rol")
public class Rol implements java.io.Serializable {

	private int idRol;
	private String nombreRol;
	private String descripcionRol;
	private Set<Usuario> usuarios = new HashSet<Usuario>(0);

	public Rol() {
	}

	public Rol(int idRol, String nombreRol, String descripcionRol) {
		this.idRol = idRol;
		this.nombreRol = nombreRol;
		this.descripcionRol = descripcionRol;
	}

	public Rol(int idRol, String nombreRol, String descripcionRol, Set<Usuario> usuarios) {
		this.idRol = idRol;
		this.nombreRol = nombreRol;
		this.descripcionRol = descripcionRol;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "id_rol", unique = true, nullable = false)
	public int getIdRol() {
		return this.idRol;
	}

	public void setIdRol(int idRol) {
		this.idRol = idRol;
	}

	@Column(name = "nombre_rol", nullable = false, length = 45)
	public String getNombreRol() {
		return this.nombreRol;
	}

	public void setNombreRol(String nombreRol) {
		this.nombreRol = nombreRol;
	}

	@Column(name = "descripcion_rol", nullable = false, length = 100)
	public String getDescripcionRol() {
		return this.descripcionRol;
	}

	public void setDescripcionRol(String descripcionRol) {
		this.descripcionRol = descripcionRol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Set<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

}
