package com.matoosfe.ecommerce.modelo;
// Generated 05/06/2019 19:11:01 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cliente generated by hbm2java
 */
@Entity // Anotación para representar una entidad que manipula información - obligatorio
/*
 * Anotación para denotar a cual tabla representa la clase, es opcional y se
 * coloca cuando el nombre de la clase es diferente al de tabla.
 */
@Table(name = "tipo_cliente")
public class TipoCliente implements java.io.Serializable {

	private int idTipcli;
	private String nombreTipcli;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public TipoCliente() {
	}

	/**
	 * @param idTipcli
	 * @param nombreTipcli
	 */
	public TipoCliente(int idTipcli, String nombreTipcli) {
		this.idTipcli = idTipcli;
		this.nombreTipcli = nombreTipcli;
	}

	/**
	 * @return the idTipcli
	 */
	@Id // Anotación que representa la PK y es obligatorio
	@GeneratedValue(strategy = GenerationType.IDENTITY) // Como se genera esa clave, IDENTITY es automático
	@Column(name = "id_tipcli", unique = true, nullable = false)
	public int getIdTipcli() {
		return idTipcli;
	}

	/**
	 * @param idTipcli the idTipcli to set
	 */
	public void setIdTipcli(int idTipcli) {
		this.idTipcli = idTipcli;
	}

	/**
	 * @return the nombreTipcli
	 */
	@Column(name = "nombre_tipcli")
	public String getNombreTipcli() {
		return nombreTipcli;
	}

	/**
	 * @param nombreTipcli the nombreTipcli to set
	 */
	public void setNombreTipcli(String nombreTipcli) {
		this.nombreTipcli = nombreTipcli;
	}

	/**
	 * @return the clientes
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoCliente")
	public Set<Cliente> getClientes() {
		return clientes;
	}

	/**
	 * @param clientes the clientes to set
	 */
	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
